[package]
name = "rust_nn"
version = "0.1.0"
authors = ["Marcell Perger"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall_double = "^0.3.0"
mockall = "^0.11.2"


[dev-dependencies]
